version: '3'
services:
  next:
    build: 
      context: .
      dockerfile: ./NodeDockerFile
    container_name: the_world_data
    expose:
      - 3000
      - 9229
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ../Source/app:/app
    tty: true
# node_modules ディレクトリはNodeJS系PJのライブラリファイル等を格納するディレクトリとなっているが、
# 当ディレクトリはReadWriteが非常に多い大きい為、Dockerを使用する上でパフォーマンス悪化の原因となる可能性がある。
# そのため、環境パフォーマンス問題が顕在化してきた場合に備え volume trick を使用した当ディレクトリのホストへのReadWriteをさせない実装を残しておく。
# volumes:
#   node_modules: